### ISSUE TITLE
Bluetooth Devices Disconnecting from iPhone after Herald update

### ISSUE THREAD

**Issue by HendX** [AU-COVIDSafe/mobile-ios#38] opened 2020-12-21 21:44 UTC
It has already been mentioned in #9, but since this is potentially a regression for a previously fixed bug, or even a new bug, I think it's prudent to open a new issue to separate it from the old reports.

There are numerous reports of the Herald update causing interference with other Bluetooth devices.

I have experienced this myself after updating the app over the weekend:

1. I was unable to unlock my car using my iPhone. Typically this is very reliable, but for the first time ever I had to turn off/on Bluetooth on my phone to get this working again.

2. Upon attempting to use the new "Fitness+" app on Apple TV, my Apple Watch was unable to connect to the app on Apple TV. The Apple Watch connects to the Apple TV via the iPhone using Bluetooth.
   
   At the same time, my wife was also using the app and had no problem connecting in the same manner. She does not have the COVIDSafe update installed.

---

Other reports on #9 since the Herald update:

* @arthurhsliu - Apple Watch / AirPods
* @wabzqem - Apple Watch
* @beaugiles - Beddit Sleep Monitor, Withings Bluetooth Thermometer

---

Users will not use this app if it interferes with their devices, such as:

* Other Apple peripherals (Apple Watch, AirPods)
* Medical devices (such as continuous glucose monitors)
* Security devices (such as locks on cars, offices, or even locks on public scooter helmets)

---

I would also like to point out that I raised this as a distinct possibility in #34 on December 4, a full two weeks before the update was released.

> In fact, it is entirely possible that a variation of #9 will surface due to the way the keep-alive works. This can't be verified yet, without a larger field trial and/or raw data to analyse.

---

It is clear that this update was rushed out without adequate testing (as has been a pattern with this app). It is also clear that the legitimate concerns raised here on GitHub have not been treated with the respect and seriousness they deserve.

Note also that the DTA blog post defending not using ENF once again includes incorrect and misleading information about how the framework works.

https://www.dta.gov.au/news/covidsafe-uses-herald-protocol-improve-app-performance:

> The ENF, as the name suggests, focuses primarily on notifying individuals who may have been exposed to COVID-19. 

Quite frankly, this is utter rubbish, and the anonymous person responsible for writing this is misleading the public. 

Once again, it is not a requirement to work in this manner. Competent developers are able to make it work in a very similar manner to how COVIDSafe currently works.

---

Recommended fix for this bug:

**Migrate to Exposure Notifications Framework** as an immediate course of action.

**Comment by wabzqem** [comment] 2020-12-21 22:08
A few times since the COVIDSafe 2.0 update, my Apple Watch has lost connectivity with my phone. I don’t think it’s the same issue as issue #9 though (i.e. too many pending connections). Twice the connection to my watch recovered on its own, and once it reconnected okay when I tapped “connect” in the Bluetooth settings on my phone. But I’ve also seen it unable to reconnect when manually attempted.

Here’s a screenshot from the most recent occurrence. 

![image](https://user-images.githubusercontent.com/1582274/102826612-23d43f80-4435-11eb-975b-1d4b9e3d8297.jpeg)

All of the unnamed devices are from COVIDSafe. What’s interesting here is that I don’t believe there are actually 3 distinct iPads that have COVIDSafe installed, but it continued to show this for some time. I’ve also seen it say it’s connected to 4 iPads. I’ve installed COVIDSafe on only two iPads to try to reproduce this. I also don’t believe there are that many iPhones around but it’s plausible they could be my neighbours’, the iPads less so.

I don’t know exactly what’s causing this yet, but it’s clear something is going awry so it’s worth investigating.

**Comment by jimmo** [comment] 2020-12-22 02:38
FYI here's a potential area that you should investigate (thanks @yaakov-h @HendX @wabzqem ). I haven't tested this, but it should be fairly easy to replicate and inspect the logs. And in particular, if (as the Herald developers have commented) that the warning below is being logged, then it's a good sign that there's something in this area.

Herald on iOS will attempt to link devices by both their payload and their pseudo address. The thing to be very careful of is that any time you initiate a connection to a device, you must call `cancelPeripheralConnection` otherwise iOS will just keep trying indefinitely in the background. (This is the core of #9 ).

The Android app caches its payload by remote address. Additionally, the Android app doesn't attempt to synchronise RPA rotation with changing the ephemeral key (or clearing the address->payload cache). (I've raised this many times before, please fix).

So what this means is that when an Android rotates its RPA, it will have a different address, and different pseudo address, but the same payload. So the iOS client will still attempt to link them.

There are two racing tasks doing cleanup:

taskRemoveDuplicatePeripherals will attempt to remove devices that are linked by their payload
https://github.com/vmware/herald-for-ios/blob/develop/herald/herald/Sensor/BLE/BLEReceiver.swift#L305
This runs every 8 seconds.

taskRemoveExpiredDevices will attempt to cancel pending connections.
https://github.com/vmware/herald-for-ios/blob/develop/herald/herald/Sensor/BLE/BLEReceiver.swift#L291
This also runs every 8 seconds, but only on devices that haven't done anything for 120 seconds.

So you could have a scenario where a device rotates its RPA, keeping its existing payload. Herald will continue to attempt to re-connect to the old address, but before it has a chance to cancel the connection in taskRemoveExpiredDevices, taskRemoveDuplicatePeripherals will remove the database entry once it also sees the same payload on the new address.

Note the giant warning in https://github.com/vmware/herald-for-ios/blob/develop/herald/herald/Sensor/BLE/BLEReceiver.swift#L333 -- if this log message ("did you forget to cancel the connection") is being shown then that definitely sounds like a potential cause for concern.

**Comment by jimmo** [comment] 2020-12-22 02:43
A fairly easy way to test this would be to put a COVIDSafe 2.0 build onto a few Android phones and change `BLESensorConfiguration.advertRefreshTimeInterval` down to a small value like 20 seconds.

**Comment by jxeeno** [comment] 2020-12-22 10:50
So this seems like the right issue to post this in?

* I've got production 2.0 build on my Android phone (Pixel 2 XL).
* In the past, I've paired my phone with my computer - currently running Mac OS 10.15
* My Mac now shows ~24 Pixel 2 XL "devices" in the devices list (see screenshot below).  Each has a different MAC address.
* I'm certain I don't have 24 Pixel 2 XLs within Bluetooth range which I've paired to in the past.
* Every couple of minutes, a new Pixel 2 XL "device" appears in my Bluetooth devices list

![image](https://user-images.githubusercontent.com/23213119/102880462-74808280-449f-11eb-8d4b-d5f797ecbc05.png)

**Comment by yaakov-h** [comment] 2020-12-22 10:52
That's hilarious, but it probably belongs in an issue in the mobile-android repo, not the mobile-ios one.

Unless you have iOS running on a Pixel, in which case... how? 😄

**Comment by jimmo** [comment] 2020-12-22 12:54
I found another likely cause of the Bluetooth stack locking up...

- Once a device goes out of range, it will get a didDisconnectPeripheral. This clears the characteristics and then attempts a reconnect.
- Subsequently, taskIosMultiplex will keep attempting further re-connects.
- Each time it will do a cancelPeripheralConnection because > 12 second has passed.
- This will fire didDisconnectPeripheral, which starts the process again.

The key thing is that clearing the characteristics causes the lastUpdated field in the BLEDevice to be updated to now. This prevents taskRemoveExpiredDevices from ever being able to remove the device from the database.

So for every device that goes out of range, you end up with a loop that is continually connecting and then cancelling. The connection limit doesn't help because it isn't aware of pending connection. Eventually you get into a state where you have enough concurrent connections for the iOS stack to stop (as in #9 ).

@wabzqem shared a log file with me that showed two things:
 - For any given device, after running as normal, it then goes into this loop.
 - taskRemoveExpiredDevices never expired any devices, until the device was paused in the debugger long enough to allow lastUpdated to be more than 2 minutes ago, then immediately after resuming from the debugger, a bunch of devices were expired.

I just went to report this upstream in Herald, but it seems that they already possibly figured this out (although the commit/PR message doesn't give any indication of what it fixes -- "Minor efficiency update").  https://github.com/vmware/herald-for-ios/issues/86

**Comment by covidsafe-team** [comment] 2020-12-22 23:48
Thanks @HendX @jimmo @wabzqem for raising this issue. We have prioritised addressing this issue and will provide an update on progress. We've also engaged with the Herald developers on this issue. Thanks @jimmo for all the additional insights you've provided.

**Comment by covidsafe-team** [comment] 2020-12-23 02:58
Thank you to @HendX @jimmo @wabzqem. We have now applied the suggested fix and Apple has approved the update today. We will keep this issue open to monitor the fix and will close this issue once the fix is validated. We have also added a number of other issues that you've raised to our backlog   - thank you for your ongoing support.

**Comment by yaakov-h** [comment] 2020-12-23 03:45
@covidsafe-team I assume you'll be updating the source code with the 2.1 release soon?

**Comment by HendX** [comment] 2020-12-23 03:52
> once the fix is validated

Was it not validated before releasing the update?

**Comment by HendX** [comment] 2020-12-23 04:05
The update is now visible for me, so I will run the update over the coming days and check my car and Apple Watch.

**Comment by covidsafe-team** [comment] 2020-12-23 05:33
@yaakov-h - we will release the code shortly and thanks @HendX, we have tested this prior to release and thank you for doing some checks over the next couple of days.

**Comment by covidsafe-team** [comment] 2020-12-23 06:49
@yaakov-h we've released the code

**Comment by HendX** [comment] 2020-12-23 07:41
> @yaakov-h we've released the code

Is the code released for 2.1 or 2.1.1? What's the difference between these versions?

**Comment by covidsafe-team** [comment] 2020-12-24 03:21
@HendX - the code released is for 2.1.1, which is the latest version. We fixed a UI issue in 2.1.

**Comment by HendX** [comment] 2020-12-28 22:04
# Version 2.1 Observations

I've been running COVIDSafe 2.1 and 2.1.1 since they were released and I have a few observations.

## Versioning

I don't quite understand what happened with the versioning from 2.1 to 2.1.1.

> We fixed a UI issue in 2.1.

Based on the timing of each release and how the version numbers were incremented, I suspect this isn't the real explanation, which really does make me question the software development processes used for this app.

## Bluetooth Reliability

I installed 2.1 as soon as it was available. My car would still not unlock after running this update. 

2.1.1 seems to resolve the connectivity issues. I haven't experienced the same issue since installing 2.1.1.

**However**, I have noticed a new strange behaviour:

* After exiting my car, typically it locks itself when I go out of range (let's say 10 metres away or so).
* After using 2.1.1, my car auto-locked upon exit while I was standing directly beside the car. This has never happened before, which indicates some interference or issue with Bluetooth.
* This doesn't occur every time, so is not easily replicable

## Background Processing

The use of `CoreLocation` does indeed seem to make the app run 100% of the time.

**This is a gross misuse of Apple APIs**, which leads me to several observations:

1. It appears the phone constantly being awake causes other apps to receive more background processing time.
2. My phone battery is draining at a far quicker rate. The drain can't be directly attributed to COVIDSafe, but I believe COVIDSafe is the root cause of the overall drain, as other apps are now doing more work as a result.
3. Other apps seem to not be updating in the background at all, when they previously would

I'm not sure how to reconcile points 2 and 3, other than say it feels like my phone is acting wacky.

Last 10 days:

![IMG_0978](https://user-images.githubusercontent.com/525190/103245588-90f55100-49b0-11eb-9f13-4118f8d1289a.PNG)

Last 24 hours (v2.1.1 installed 24/12):

![IMG_0979](https://user-images.githubusercontent.com/525190/103245586-8dfa6080-49b0-11eb-8520-740e5bdb84cd.PNG)

iOS should not be behaving like this.

## Location Services

I received a system notification after 3 days telling me that COVIDSafe has used my location a number of times. The strange part about this notification is how few locations there are reported. I suspected this is due to COVIDSafe subsequently keeping itself alive, thereby not giving the system and opportunity to wake the app (since it's already awake).

![IMG_0947](https://user-images.githubusercontent.com/525190/103245540-6b684780-49b0-11eb-94f4-2c848fe9c0ff.jpg)


## Conclusion

Yes, I know the Herald update has passed app review 3 times now, but I think if Apple knew what effect this was happening on their devices it could easily be rejected on the grounds that it is missing APIs and misusing background processing time.

Especially given that the Federal Government is encouraging their entire population to install software that adversely affects their devices.

Recommendation: ENF. Now. Do it.

**Comment by covidsafe-team** [comment] 2021-02-02 00:23
Thanks for the feedback. A new version of COVIDSafe was released today which includes further updates to the app. We will continue to monitor performance and make improvements in future releases.

**Closed by covidsafe-team** 2021-02-02 00:23 UTC

**Comment by HendX** [comment] 2021-02-02 00:44
Thanks. I would note that #42 doesn't contain a single change that relates to how the Bluetooth functionality operates, other than some minor window dressing.

**Comment by steve-taylor** [comment] 2021-06-09 04:02
> Thanks. I would note that #42 doesn't contain a single change that relates to how the Bluetooth functionality operates, other than some minor window dressing.

You’re talking to a brick wall. They’re never, ever going to use ENF, because they’ve publicly stated they won’t use it, and they think changing their minds makes them look weak.

I would raise your findings with Apple if you haven’t done so already.
