### ISSUE TITLE
COVIDSafe tries to connect to every device it's ever connected to, indefinitely

### ISSUE THREAD

**Issue by wabzqem** [AU-COVIDSafe/mobile-ios#9] opened 2020-07-05 10:57 UTC
Every time the central controller disconnects from a peripheral (e.g. after a successful exchange) it will [attempt to reconnect 15 seconds later](https://github.com/AU-COVIDSafe/mobile-ios/blob/6f92ff8fb8a16dd127039ef5f8ef39219b08785b/CovidSafe/CentralController.swift#L239), no matter what reason it disconnected for. When devices go out of range or switch identifier, these connections will stay pending indefinitely.

According to [Apple's documentation](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/1518766-connect):

> Attempts to connect to a peripheral don’t time out.

There doesn't seem to be anywhere where the central controller cancels pending connections (except when bluetooth is powered back on, rarely), so it seems to me that COVIDSafe will be attempting to connect to a potentially massive amount of peripherals.

This is almost certainly the cause of COVIDSafe causing some (maybe not all) issues with connections to Apple Watch and other devices. I noticed device-disconnects occurring more frequently when 1.2 was released (and when this bug was introduced), but assumed that was because the app was connecting more as the first background bug was fixed. Now I realise it's probably because this bug was introduced at the same time.

**Comment by covidsafe-support** [comment] 2020-07-06 00:33
Hi @wabzqem - thank you for bringing this to our attention. We're currently looking into this and will update this issue when we have more information.

**Comment by jimmo** [comment] 2020-07-06 01:06
> This is almost certainly the cause of COVIDSafe causing some (maybe not all) issues with connections to Apple Watch and other devices. I noticed device-disconnects occurring more frequently when 1.2 was released (and when this bug was introduced), but assumed that was because the app was connecting more as the first background bug was fixed. Now I realise it's probably because this bug was introduced at the same time.

With the assumption (based on what @wabzqem is describing above) that COVIDSafe is ending up in a state where it has lots of "in progress" pending connections, I was able to make a demo using two popular BLE scanner apps ("nRF Connect" and "BLE Scanner") that could show how this explains the commonly-reported issue that COVIDSafe is interfering with other devices.

1. Using whatever means, make nRF Connect find ~100s of devices. (e.g. a device that changes its MAC every second or something).
2. Initiate a connection to each of them (each device will be stuck in the pending state, assumed to be the same as what COVIDSafe is doing as described above).
3. Try and connect to a different device from BLE Scanner. Past some number of pending connections in nRF Connect, BLE Scanner will be unable to connect.
4. Force quit nRF Connect.
5. BLE Scanner will immediately be able to connect to that other device.

**Comment by c19x** [comment] 2020-07-08 15:31
Dear COVIDSafe, I've created a solution that supports constant background scanning and device proximity tracking on iOS and Android. The contact tracing app will work on 81.56% of devices globally without software upgrade to latest version. It does not rely on the Google + Apple API as I fear many users won't or can't upgrade their OS, thus it will only work on a theoretical maximum of 76.98% of devices today. The Bluetooth beacon underpinning the solution will work on 98.74% of devices globally (June 2020). It can even handle Android devices that can only act as a central, not a peripheral (e.g. Samsung J6). Please take a look at https://github.com/c19x

The scan-connect-read-disconnect-pendingConnect|scan approach in COVIDSafe on iOS will fail when both devices are in background state (i.e. app not in foreground, device is locked) which will be the norm. They simply won't detect each other, until one of them comes to the foreground. Try the following ...

Failure condition 1
1. iPhone A and B in separate faraday bags (i.e. out of range of each other)
2. Take A out, install and start app on A, move app to background, lock device, place back in faraday bag
3. Take B out, install and start app on B, move app to background, lock device, place back in faraday bag
4. Wait 30 minutes. This is equivalent to two isolated users installing their app and venturing out later
5. Take A and B out, they won't detect each other until either A or B brings app to foreground

Failure condition 2
6. Continuing from 5, now that A and B are together and detecting each other.
7. Move app on A and B to background, lock devices. Place A in faraday bag
8. Wait 30 minutes. This is equivalent to two people meeting, then going out of range of each other for a while.
9. Take A out of faraday bag, they won't detect each other until either A or B brings app to foreground

This, and other related issues, have been investigated and a solution has been developed and documented for sharing. Please take a look at https://github.com/c19x/C19X-iOS-BLE

Best regards and good luck 👍

**Comment by rizidis** [comment] 2020-07-20 06:06
We also concur with @wabzqem that COVIDSafe is consuming *limited* Bluetooth resources unnecessarily when it attempts to reconnect with peripherals (other COVIDSafe instances) that are history. When our fitness app cannot connect to Bluetooth heart monitors (logs show waiting for didConnect callbacks from central), simply shutting-down (and restarting) COVIDSafe immediately restores heart monitor connections. We have verified this numerous times in home office where COVIDSafe should definitely not have pending connections (CentralController.swift, line239). Surely this bug would also be limiting COVIDSafe's performance and effectiveness? Perhaps you could simply timeout pending connections (as we do)?

**Comment by c19x** [comment] 2020-07-21 10:15
Dear @rizidis, you are entirely correct. Pending connects serve limited purpose for reconnecting an iOS central to an iOS peripheral if the devices are not reconnected within a few minutes, as the iOS peripheral will be referenced under a new peripheral identifier after about 20-30 minutes of being idle (i.e going out of range). The same is also true for Android peripherals, albeit the period is usually longer. The indefinite pending connect is only meaningful for an iOS central to reconnect to devices with a fixed identifier (like the door lock example in Apple doc). Regular housekeeping to remove pending connections that have been inactive for some time is a good idea. Not entirely sure why these pending connections are impacting your fitness app tho, would shutting-down COVIDSafe (not restarting) restore your app's connections, or does it have to include a restart?

**Comment by JoachimC** [comment] 2020-07-21 13:03
I often have problems connecting my bluetooth heart rate monitor to my iPhone (apps: Polar Beat and Garmin Connect) and this is normally resolved by closing COVIDSafe. Not a great scenario given the times I'm using my heartrate monitor is when I'm leaving the house and should be running COVIDSafe!

**Comment by jimmo** [comment] 2020-07-21 14:51
@covidsafe-support 

I noticed that the code for v1.8 was published today and became available in the app store a short while later. Although the code in CentralController has changed, I do not believe this issue is fixed.

To re-iterate @wabzqem's quote from the documentation -- "Attempts to connect to a peripheral don’t time out." ([ref](https://developer.apple.com/documentation/corebluetooth/cbcentralmanager/1518766-connectperipheral?)). Additionally, the didFailToConnect event is only called if an transient error occurred during connection, so cleaning up there doesn't help. Apple's documentation says:

> The manager invokes this method when a connection initiated with the connect(_:options:) method fails to complete. Because connection attempts don’t time out, a failed connection usually indicates a transient issue, in which case you may attempt connecting to the peripheral again.

([ref](https://developer.apple.com/documentation/corebluetooth/cbcentralmanagerdelegate/1518988-centralmanager))

So it's not clear how the new code can fix this issue, but just to be really sure, I used almost the same scenario described in my earlier post, but with COVIDSafe rather than nRF Connect. On a test phone, carefully shielded from and out of range of other devices, with empty payloads, I have a "fake COVIDSafe" peripheral that changes its MAC after every connection. After ~200 connections, it became unable to make further connections, and other apps similarly become unable to connect other devices. Terminating and relaunching COVIDSafe or turning off/on Bluetooth made it resume. Was able to reproduce this several times, and one one occasion I let it stay in the stuck state for over 45 minutes and it was not able to recover on its own.

I suggest adding some sort of timeout to any locations in the code that call connectPeripheral. @wabzqem do you have a suggestion on the best way to implement this?

**Comment by wabzqem** [comment] 2020-07-21 15:08
I came to exactly the same conclusion as @jimmo after reading the diff - I don't believe this issue is fixed.

I would recommend keeping track of peripherals that are being connected to with `connect(_ peripheral: CBPeripheral, options: [String : Any]? = nil)`, remove from the set when `centralManager(_ central: CBCentralManager, didConnect peripheral: CBPeripheral)` is called, and then explicitly cancel and remove any connections that have been in this set for too long. You may need to use other bluetooth callbacks to trigger the cancellations as doing this in the background otherwise may be tricky.

The comment in `didDisconnectPeripheral`:
> // An error may represent that the peripheral is out of range, BL is OFF etc. In that case we don't want to retry.

Is probably misguided. As soon as an exchange is made, the peripheral is quickly disconnected so this is run with a `nil` error. This function won't run when a pending connection peripheral is out of range, as it's never connected to begin with.

**Comment by wabzqem** [comment] 2020-07-22 00:08
Just to add, I installed 1.8 yesterday evening. By 9am this morning (after going out) my Apple Watch had disconnected and wouldn't reconnect. Killing COVIDSafe and opening it again allowed the watch to connect again.

**Comment by rizidis** [comment] 2020-07-22 01:59
> Dear @rizidis, you are entirely correct. Pending connects serve limited purpose for reconnecting an iOS central to an iOS peripheral if the devices are not reconnected within a few minutes, as the iOS peripheral will be referenced under a new peripheral identifier after about 20-30 minutes of being idle (i.e going out of range). The same is also true for Android peripherals, albeit the period is usually longer. The indefinite pending connect is only meaningful for an iOS central to reconnect to devices with a fixed identifier (like the door lock example in Apple doc). Regular housekeeping to remove pending connections that have been inactive for some time is a good idea. Not entirely sure why these pending connections are impacting your fitness app tho, would shutting-down COVIDSafe (not restarting) restore your app's connections, or does it have to include a restart?

**Comment by rizidis** [comment] 2020-07-22 02:08
Hi c19x, just to clarify I should have said shutting-down and "relaunching" COVIDSafe immediately restores heart monitor connections - not "restarting" - although restarting iphone also works! We also note toggling Bluetooth off/on in system settings did not help.

**Comment by BeauGiles** [comment] 2020-08-04 05:41
This appears to be fixed as of v1.9?

**Comment by covidsafe-support** [comment] 2020-08-06 00:55
Hi @wabzqem - just letting you know we have released v1.9 of COVIDSafe for iOS which should have addressed this issue, please let us know if you believe otherwise. Thank you again for reporting this issue.

**Closed by covidsafe-support** 2020-08-06 00:55 UTC

**Comment by wabzqem** [comment] 2020-08-06 08:52
It looks good to me. I've been running it since updating on Monday afternoon and I haven't had it disconnect. Others on twitter, whirlpool etc see the same. This is a great improvement!

**Comment by arthurhsliu** [comment] 2020-12-19 22:04
It looks like this bug (or some variant) is back since COVIDSafe v2.0's Herald update, both Apple Watch and AirPods Pro are disconnecting from the phone and only reconnecting upon Bluetooth stack restart when COVIDSafe is running.

**Comment by jimmo** [comment] 2020-12-19 22:58
@arthurhsliu This is possibly even a known issue in Herald... it's hard to tell.
https://github.com/vmware/herald-for-ios/issues/15#issuecomment-747910006

**Comment by wabzqem** [comment] 2020-12-19 22:59
I haven't reproduced this on COVIDSafe 2.0, but the response to https://github.com/vmware/herald-for-ios/issues/15 is extremely concerning. Has this been checked?

**Comment by wabzqem** [comment] 2020-12-20 00:41
I have an iPhone 11 running iOS 14.2, and this morning my Apple Watch lost connection and is not reconnecting. This has not happened since this fix in August. Please stop using a connection based solution and switch to EN.

**Comment by HendX** [comment] 2020-12-20 20:45
Anecdotally, this morning my iPhone 12 Pro Max was unable to unlock my car using Bluetooth.

Restarting the Bluetooth stack fixed the issue.

This is an extremely rare occurrence. The only time I can remember this happening previously was when I was logged out of my account.

The only change made since I last drove the car on Friday was the COVIDSafe update.

Request reopening of this issue.

**Comment by HendX** [comment] 2020-12-20 23:40
Anecdote 2:

On Saturday afternoon, I was trying out the new Apple TV "Fitness+" app. This is a new app from Apple that commences by connecting directly to your Apple Watch.

My watch was unable to connect, but my wife's was able to. She doesn't have the app installed. It only occurs to me now that it was likely due to me running COVIDSafe.

---

Tangent: If your followup question is "why doesn't your wife has the app installed?", precisely because of these kinds of shenanigans.

**Comment by BeauGiles** [comment] 2020-12-20 23:43
My Beddit Bluetooth sleep monitor would not connect last night after updating COVIDSafe.

My Withings Bluetooth thermometer also refuses to connect following the COVIDSafe update.

There was no issue with either prior to updating COVIDSafe on the weekend.

**Comment by yaakov-h** [comment] 2020-12-21 10:32
[The plural of anecdote is data.](http://blog.danwin.com/don-t-forget-the-plural-of-anecdote-is-data/) There is sufficient evidence already above and further online that the Herald update has reintroduced this critical bug, which drives adoption downwards and will negatively affect COVIDSafe's efficacy.

This should be fixed as a matter of urgency or the Herald update reverted until it can be resolved.

**Comment by covidsafe-team** [comment] 2020-12-22 00:12
Thanks for the comments here - we are currently investigating this issue. Please move further comments into #38. At this point we are collecting data and trying to replicate the issue.
